-- Issue #99. `0011_event_assignees.sql` created the junction table empty:
-- every event already in the database got no assignment row at all, so
-- `assignees_for_events` returned `[]` for it and the dashboard's
-- "Prochains événements" card (apps/web/src/routes/home.rs, `agenda_row`)
-- painted a bare "?" ring followed by an em dash and nothing — on *every*
-- pre-#73 event, until someone re-edited it.
--
-- The assignment those rows should have had is the one #73 chose as the
-- default for a new event: its creator (apps/api/src/agenda/events.rs,
-- `resolve_assignees`, which falls back to `[creator]` on the same terms).
-- Backfilling it is a data fix, not a schema change, so it lands as its own
-- migration rather than an edit to 0011.
--
-- The `NOT EXISTS` guard is load-bearing, and `ON CONFLICT DO NOTHING` is
-- not a substitute for it: the conflict target is (event_id, user_id), so a
-- plain `SELECT id, created_by FROM events` would happily *add* the creator
-- to an event somebody had deliberately assigned to someone else — turning
-- "assigné à Robin" into "assigné à Camille, Robin", complete with a mixed
-- avatar colour. Only events carrying no assignment at all are touched.
-- `ON CONFLICT DO NOTHING` stays as a cheap net under a future edit of that
-- clause; with it in place the statement is a no-op on every re-run.
--
-- READ THIS BEFORE RELYING ON THIS FILE: what it repairs depends entirely on
-- the role that applies it. Until #105 that role was the wrong one, and this
-- file is where that was first written down. The paragraphs below are that
-- history, not a live caveat -- #105 closed it, and no database had recorded
-- this migration as applied when it did.
--
-- Until #105 there was no separate migration role: `sqlx::migrate!(
-- "./migrations").run(&db)` ran on the *runtime* pool (apps/api/src/main.rs),
-- i.e. under `DATABASE_URL` -- and README.md's "Deployment note on Row-Level
-- Security" prescribes exactly one role for that URL: `CREATE ROLE app_role
-- LOGIN ... NOSUPERUSER NOBYPASSRLS`. Such a role owns these tables but does
-- not bypass `FORCE ROW LEVEL SECURITY`, so the *source* of this INSERT --
-- `FROM events e` -- was filtered to zero rows by `events_isolation`
-- (0002_agenda.sql), whose predicate reads a per-request `app.family_id`
-- that is unset during a migration. Nothing was selected, so nothing was
-- inserted and the `WITH CHECK` side was never even reached: no error, no
-- warning.
--
-- Measured, not feared: with `0001..0012` applied by such a role (owner of
-- the tables, `relforcerowsecurity = t`, `rolsuper = f`, `rolbypassrls = f`)
-- over a database holding events with no assignment, this file reported
-- `INSERT 0 0`, exited 0, left them unassigned, and was then recorded as
-- applied -- so it would never have run again. The failure was silent and
-- permanent. No CI gate caught it either: ci.yml and infra/docker-compose.yml
-- both migrate as a superuser role, where this statement does work.
--
-- What #105 changed: migrations no longer run on the runtime pool at all.
-- They run on their own connection (`MIGRATION_DATABASE_URL`,
-- apps/api/src/migrations.rs), as a role that owns the tables *and* carries
-- `BYPASSRLS`; the variable is required with no `DATABASE_URL` fallback, and
-- the pass refuses to start unless that connection provably bypasses RLS.
-- So wherever the API boots at all, this statement is now reached with its
-- source visible. `apps/api/tests/migration_role_flow.rs` holds both halves
-- of that as tests: the statement below applying to zero rows under a
-- NOBYPASSRLS owner, and to one row under a BYPASSRLS role.
--
-- The consequence for #99: this file is *not* what fixes it. The fix that
-- holds everywhere is the display fallback in `row_assignee_ids`
-- (apps/web/src/routes/home.rs) -- an event that reaches the dashboard with
-- no assignee is rendered in its creator's colour token, and named after the
-- creator whenever the member roster can be resolved; when it cannot (roster
-- fetch failed, or the creator has left the family) the name degrades to
-- "Membre" and the initial to "M", which is the app-wide degradation of
-- `author_name`, not something this fallback adds.
--
-- What this backfill does repair, now that it is reached everywhere, is the
-- rows that exist at the moment it runs. That is all it can ever be: not
-- "once and for good", and not a second line of defence for anyone. A
-- migration runs once, so every event created *after* it with no assignment
-- row is beyond its reach -- which the Google Calendar import produced on
-- every import until #106/#147 (apps/api/src/google_calendar/imports.rs
-- inserted into `events` and never into `event_assignees`; it now writes the
-- assignee and catches up the rows it wrote before). The display fallback
-- above is what covers whatever arrives that way next.
INSERT INTO event_assignees (event_id, user_id)
SELECT e.id, e.created_by
FROM events e
WHERE NOT EXISTS (
    SELECT 1 FROM event_assignees ea WHERE ea.event_id = e.id
)
ON CONFLICT DO NOTHING;
