#!/usr/bin/env python3
"""Builds `off-categories-fr.tsv.gz` from Open Food Facts' category taxonomy (#406).

The recipe suggestions (`apps/api/src/recipes/taxonomy.rs`) match an
ingredient to what is in stock through this file: one line per category,

    <tag id> TAB <parent ids, comma-separated> TAB <French names, |-separated>

Kept: every category with a French name or synonym, and every ancestor of
one (so a descent from a scanned product's category to a recipe's is never
cut). Parents outside that set are dropped. Lines are sorted by id and the
gzip header carries no timestamp, so the same taxonomy gives the same bytes.

Usage (Python 3 standard library only):

    python3 apps/api/data/build_off_categories.py [categories.full.json]

Without an argument the taxonomy is downloaded from
https://static.openfoodfacts.org/data/taxonomies/categories.full.json.

The data is Open Food Facts', under the Open Database License (ODbL 1.0):
see README.md next to this script.
"""

import gzip
import json
import os
import sys
import urllib.request

SOURCE = "https://static.openfoodfacts.org/data/taxonomies/categories.full.json"
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "off-categories-fr.tsv.gz")


def french_names(entry):
    names = []
    seen = set()
    candidates = []
    if entry.get("name", {}).get("fr"):
        candidates.append(entry["name"]["fr"])
    candidates.extend(entry.get("synonyms", {}).get("fr", []))
    for name in candidates:
        name = name.strip()
        # The separators of the format never occur in a name we keep.
        if not name or any(c in name for c in "\t|\n\r"):
            continue
        if name.lower() not in seen:
            seen.add(name.lower())
            names.append(name)
    return names


def main():
    if len(sys.argv) > 1:
        with open(sys.argv[1], encoding="utf-8") as f:
            taxonomy = json.load(f)
    else:
        with urllib.request.urlopen(SOURCE) as resp:
            taxonomy = json.load(resp)

    keep = {tag for tag, entry in taxonomy.items() if french_names(entry)}
    stack = list(keep)
    while stack:
        for parent in taxonomy[stack.pop()].get("parents", []):
            if parent in taxonomy and parent not in keep:
                keep.add(parent)
                stack.append(parent)

    lines = [
        "# Open Food Facts category taxonomy, French names (ODbL 1.0).",
        "# Generated by build_off_categories.py; do not edit by hand.",
    ]
    for tag in sorted(keep):
        entry = taxonomy[tag]
        parents = [p for p in entry.get("parents", []) if p in keep]
        lines.append(f"{tag}\t{','.join(parents)}\t{'|'.join(french_names(entry))}")
    data = ("\n".join(lines) + "\n").encode("utf-8")

    with open(OUT, "wb") as f:
        f.write(gzip.compress(data, compresslevel=9, mtime=0))
    print(f"{len(keep)} categories, {len(data)} bytes, {os.path.getsize(OUT)} bytes gzipped")


if __name__ == "__main__":
    main()
